---
language: node_js

node_js:
  - "8"

os:
  - linux
  - osx

install:
  - npm install

after_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run buildosx; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run build; fi
