---
language: node_js
node_js:
  - "8"
os:
  - linux
install:
  - npm install
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run build ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tar -zcvf linux64.tar.gz build/otpmanager/linux64 ; fi
